<?php

namespace Database\Seeders;

use App\Models\Asset;
use App\Models\Market;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BahrainSeeder extends Seeder
{
    /**
     * Seed the Bahrain country data: market index, markets, and assets.
     */
    public function run(): void
    {
        $this->seedMarketIndices();
        $this->seedMarkets();
        $this->seedAssets();
    }

    /**
     * Seed market index assets.
     */
    private function seedMarketIndices(): void
    {
        $indices = [
            [
                'id' => '8c319bb7-b37d-4bbf-ad50-7a766c1c573d', // Bahrain Bourse asset
                'tv_id' => 'BAHRAIN:BAX',
                'symbol' => 'BAX',
                'isin' => 'BH0000BAX',
                'type' => 'index',
                'currency' => 'BHD',
                'inv_symbol' => 'BAX',
                'inv_id' => 123460,
                'name_en' => 'Bahrain All Share Index',
                'name_ar' => 'مؤشر البحرين العام',
                'description_en' => 'The main index for the Bahrain Bourse',
                'description_ar' => 'المؤشر الرئيسي لبورصة البحرين',
                'short_description_en' => 'Bahrain Bourse Index',
                'short_description_ar' => 'مؤشر بورصة البحرين',
                'full_name' => 'Bahrain:BAX',
                'mb_url' => '/markets/BHB/indices/BAX',
                'status' => 1,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'sector_id' => null,
            ],
        ];

        foreach ($indices as $data) {
            Asset::firstOrCreate(
                ['id' => $data['id']],
                [
                    'tv_id' => ! empty($data['tv_id']) ? $data['tv_id'] : null,
                    'symbol' => $data['symbol'],
                    'isin' => $data['isin'] ?? null,
                    'logo_id' => DB::raw('gen_random_uuid()'),
                    'type' => $data['type'],
                    'currency' => $data['currency'],
                    'inv_symbol' => $data['inv_symbol'],
                    'inv_id' => $data['inv_id'],
                    'name_en' => $data['name_en'],
                    'name_ar' => $data['name_ar'],
                    'description_en' => $data['description_en'],
                    'description_ar' => $data['description_ar'],
                    'short_description_en' => $data['short_description_en'],
                    'short_description_ar' => $data['short_description_ar'],
                    'full_name' => $data['full_name'],
                    'mb_url' => $data['mb_url'] ?? null,
                    'status' => $data['status'],
                    'country_id' => $data['country_id'] ?? null,
                    'sector_id' => $data['sector_id'] ?? null,
                ]
            );
        }
    }

    /**
     * Seed markets.
     */
    private function seedMarkets(): void
    {
        $markets = [
            [
                'id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'name_en' => 'Bahrain Bourse',
                'name_ar' => 'بورصة البحرين',
                'code' => 'BHB',
                'timezone' => 'Asia/Bahrain',
                'is_active' => 0,
                'asset_id' => '8c319bb7-b37d-4bbf-ad50-7a766c1c573d',
                'tv_link' => 'stocks-bahrain',
                'trading_days' => '["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"]',
                'open_at' => '06:30:00',
                'close_at' => '10:00:00',
                'is_open' => false,
            ],
        ];

        foreach ($markets as $data) {
            Market::firstOrCreate(
                ['id' => $data['id']],
                [
                    'country_id' => $data['country_id'],
                    'name_en' => $data['name_en'],
                    'name_ar' => $data['name_ar'],
                    'code' => $data['code'],
                    'timezone' => $data['timezone'],
                    'status' => $data['is_active'],
                    'asset_id' => $data['asset_id'],
                    'tv_link' => $data['tv_link'],
                    'trading_days' => $data['trading_days'],
                    'open_at' => $data['open_at'],
                    'close_at' => $data['close_at'],
                    'is_open' => $data['is_open'],
                ]
            );
        }
    }

    /**
     * Seed stock assets.
     */
    private function seedAssets(): void
    {
        $assets = [
            [
                'id' => '025b303a-4a94-4fe4-87af-7e6098bb0281',
                'tv_id' => 'BAHRAIN:BISB',
                'symbol' => 'BISB',
                'isin' => 'BH0004648950',
                'logo_id' => 'bahrain-islamic-bank',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'BISB',
                'inv_id' => 13537,
                'name_en' => 'Bahrain Islamic Bank',
                'name_ar' => 'بنك البحرين الإسلامي ش.م.ب',
                'description_en' => 'Bahrain Islamic Bank',
                'description_ar' => 'Bahrain Islamic Bank',
                'short_description_en' => 'Bahrain Islamic Bank',
                'short_description_ar' => 'Bahrain Islamic Bank',
                'full_name' => 'Bahrain:BISB',
                'mb_url' => '/markets/BB/stocks/BISB',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '115016cd-5a00-4352-89bc-ad0560e8d983',
                'tv_id' => 'BAHRAIN:APMTB',
                'symbol' => 'APMTB',
                'isin' => 'BH0006Y11350',
                'logo_id' => 'apm-terminals-bahrain-bsc',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'APMTB',
                'inv_id' => 1138356,
                'name_en' => 'APM Terminals Bahrain BSC',
                'name_ar' => 'APM Terminals Bahrain BSC',
                'description_en' => 'APM Terminal Bahrain BSC',
                'description_ar' => 'APM Terminal Bahrain BSC',
                'short_description_en' => 'APM Terminal Bahrain BSC',
                'short_description_ar' => 'APM Terminal Bahrain BSC',
                'full_name' => 'Bahrain:APMTB',
                'mb_url' => '/markets/BB/stocks/APMTB',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '8bd6ab2c-b1cf-4258-8b1c-82f9445d5c04',
            ],
            [
                'id' => '17a65d39-c95d-4a0b-bdc7-ec2e5045eb42',
                'tv_id' => 'BAHRAIN:NBB',
                'symbol' => 'NBB',
                'isin' => 'BH0005508773',
                'logo_id' => 'national-bank-of-bahrain',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'NATB',
                'inv_id' => 13558,
                'name_en' => 'National Bank of Bahrain',
                'name_ar' => 'مصرف السلام - البحرين ش.م.ب',
                'description_en' => 'National Bank of Bahrain',
                'description_ar' => 'National Bank of Bahrain',
                'short_description_en' => 'National Bank of Bahrain',
                'short_description_ar' => 'National Bank of Bahrain',
                'full_name' => 'Bahrain:NATB',
                'mb_url' => '/markets/BB/stocks/NBB',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '224806ca-9619-453e-8d3f-28228a83df2f',
                'tv_id' => 'QSE-GNRI',
                'symbol' => 'GNRI',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'QSI',
                'inv_id' => 13185,
                'name_en' => 'QE Index',
                'name_ar' => 'مؤشر QE',
                'description_en' => 'QE Index',
                'description_ar' => 'مؤشر QE',
                'short_description_en' => 'QE Index',
                'short_description_ar' => 'مؤشر QE',
                'full_name' => 'Doha :QSI',
                'mb_url' => '/markets/QE',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '',
            ],
            [
                'id' => '2c3952da-ff75-4a6a-b198-2c3542568f76',
                'tv_id' => 'BAHRAIN:SOLID',
                'symbol' => 'SOLID',
                'isin' => 'BH0004659858',
                'logo_id' => 'solidarity-bahrain-bsc',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'SOLID',
                'inv_id' => 13528,
                'name_en' => 'Solidarity Bahrain BSC',
                'name_ar' => 'شركة البحرين الوطنية القابضة ش.م.ب',
                'description_en' => 'Solidarity Bahrain BSC',
                'description_ar' => 'Solidarity Bahrain BSC',
                'short_description_en' => 'Solidarity Bahrain BSC',
                'short_description_ar' => 'Solidarity Bahrain BSC',
                'full_name' => 'Bahrain:SOLID',
                'mb_url' => '/markets/BB/stocks/SOLID',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '39a3b4ee-f153-47b8-9739-729c78566ae7',
                'tv_id' => 'BAHRAIN:TRAFCO',
                'symbol' => 'TRAFCO',
                'isin' => 'BH0004663116',
                'logo_id' => 'trafco-group-bsc',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'GTFP',
                'inv_id' => 13552,
                'name_en' => 'Trafco Group BSC',
                'name_ar' => 'عقـارات السيف ش.م.ب',
                'description_en' => 'Trafco Group BSC',
                'description_ar' => 'Trafco Group BSC',
                'short_description_en' => 'Trafco Group BSC',
                'short_description_ar' => 'Trafco Group BSC',
                'full_name' => 'Bahrain:GTFP',
                'mb_url' => '/markets/BB/stocks/TRAFCO',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '0fd1bbaa-8060-4165-8084-3caf0ad624e6',
            ],
            [
                'id' => '3a8dba47-4bb7-4f17-9cd5-e8f961ba4be7',
                'tv_id' => 'BAHRAIN:ZAINBH',
                'symbol' => 'ZAINBH',
                'isin' => 'BH000421H896',
                'logo_id' => 'zain-bahrain-bsc',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'ZAIN',
                'inv_id' => 942784,
                'name_en' => 'Zain Bahrain BSC',
                'name_ar' => 'مجموعة ترافكو ش.م.ب',
                'description_en' => 'Zain Bahrain Bsc',
                'description_ar' => 'Zain Bahrain Bsc',
                'short_description_en' => 'Zain Bahrain Bsc',
                'short_description_ar' => 'Zain Bahrain Bsc',
                'full_name' => 'Bahrain:ZAIN',
                'mb_url' => '/markets/BB/stocks/ZAINBH',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '59049759-5928-463c-a47c-76f9aa2cf6d9',
            ],
            [
                'id' => '3e659271-dbea-422d-b859-4a43d468afa0',
                'tv_id' => 'BAHRAIN:ABC',
                'symbol' => 'ABC',
                'isin' => 'BH0008794115',
                'logo_id' => 'arab-banking-corporation',
                'type' => 'stock',
                'currency' => 'USD',
                'inv_symbol' => 'ABCB',
                'inv_id' => 13529,
                'name_en' => 'Arab Banking Corporation',
                'name_ar' => 'المؤسسة العربية المصرفية ش.م.ب',
                'description_en' => 'Arab Banking Corporation',
                'description_ar' => 'Arab Banking Corporation',
                'short_description_en' => 'Arab Banking Corporation',
                'short_description_ar' => 'Arab Banking Corporation',
                'full_name' => 'Bahrain:ABCB',
                'mb_url' => '/markets/BB/stocks/ABC',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '423be4c4-18c2-4dfe-a201-b20a52bb214b',
                'tv_id' => 'BAHRAIN:BCFC',
                'symbol' => 'BCFC',
                'isin' => 'BH0004652895',
                'logo_id' => 'bahrain-commercial-facilities',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'BCFC',
                'inv_id' => 13535,
                'name_en' => 'Bahrain Commercial Facilities',
                'name_ar' => 'إنوفست ش.م.ب',
                'description_en' => 'Bahrain Commercial Facilities Co BSC',
                'description_ar' => 'Bahrain Commercial Facilities Co BSC',
                'short_description_en' => 'Bahrain Commercial Facilities Co BSC',
                'short_description_ar' => 'Bahrain Commercial Facilities Co BSC',
                'full_name' => 'Bahrain:BCFC',
                'mb_url' => '/markets/BB/stocks/BCFC',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '462ddcd1-094a-4133-bacf-a9bf5cab403c',
                'tv_id' => 'BAHRAIN:BBK',
                'symbol' => 'BBK',
                'isin' => 'BH0004659916',
                'logo_id' => 'bbk-bsc',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'BBKB',
                'inv_id' => 13534,
                'name_en' => 'BBK BSC',
                'name_ar' => 'بنك البحرين الوطني ش.م.ب',
                'description_en' => 'BBK',
                'description_ar' => 'BBK',
                'short_description_en' => 'BBK',
                'short_description_ar' => 'BBK',
                'full_name' => 'Bahrain:BBKB',
                'mb_url' => '/markets/BB/stocks/BBK',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '52b34dbb-2d93-43fa-84f6-e6a15f7496b9',
                'tv_id' => 'BAHRAIN:SALAM',
                'symbol' => 'SALAM',
                'isin' => 'BH000A0J2481',
                'logo_id' => 'al-salam-bank',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'SALAM',
                'inv_id' => 13561,
                'name_en' => 'Al Salam Bank B.S.C',
                'name_ar' => 'المصرف الخليجي التجاري ش.م.ب',
                'description_en' => 'Al Salam Bank',
                'description_ar' => 'Al Salam Bank',
                'short_description_en' => 'Al Salam Bank',
                'short_description_ar' => 'Al Salam Bank',
                'full_name' => 'Bahrain:SALAM',
                'mb_url' => '/markets/BB/stocks/SALAM',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '672c75cf-f2aa-486f-b4d2-dfd9bd72a6cc',
                'tv_id' => 'BAHRAIN:BKIC',
                'symbol' => 'BKIC',
                'isin' => 'BH0004654263',
                'logo_id' => 'bahrain-kuwaiti-insurance-co-b-s-c',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'BKIC',
                'inv_id' => 13538,
                'name_en' => 'Bahrain Kuwaiti Insurance Co B.S.C.',
                'name_ar' => 'المجموعة العربية للتأمين ش.م.ب',
                'description_en' => 'Bahrain Kuwait Insurance Co',
                'description_ar' => 'Bahrain Kuwait Insurance Co',
                'short_description_en' => 'Bahrain Kuwait Insurance Co',
                'short_description_ar' => 'Bahrain Kuwait Insurance Co',
                'full_name' => 'Bahrain:BKIC',
                'mb_url' => '/markets/BB/stocks/BKIC',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '6fe953a7-d042-4dfc-ad88-78a0ab9aef47',
                'tv_id' => 'BAHRAIN:BMMI',
                'symbol' => 'BMMI',
                'isin' => 'BH0004648679',
                'logo_id' => 'bmmi-bsc',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'BMMI',
                'inv_id' => 13540,
                'name_en' => 'BMMI BSC',
                'name_ar' => 'شركة البحرين لمواقف السيارات ش.م.ب',
                'description_en' => 'BMMI BSC',
                'description_ar' => 'BMMI BSC',
                'short_description_en' => 'BMMI BSC',
                'short_description_ar' => 'BMMI BSC',
                'full_name' => 'Bahrain:BMMI',
                'mb_url' => '/markets/BB/stocks/BMMI',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '0fd1bbaa-8060-4165-8084-3caf0ad624e6',
            ],
            [
                'id' => '76242227-09fc-42d1-b80a-ce161a31ecd3',
                'tv_id' => 'BAHRAIN:GHG',
                'symbol' => 'GHG',
                'isin' => 'BH0004649933',
                'logo_id' => 'gulf-hotels-group',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'GHG',
                'inv_id' => 943631,
                'name_en' => 'Gulf Hotels Group',
                'name_ar' => 'Gulf Hotels Group',
                'description_en' => 'Gulf Hotel Group BSC',
                'description_ar' => 'Gulf Hotel Group BSC',
                'short_description_en' => 'Gulf Hotel Group BSC',
                'short_description_ar' => 'Gulf Hotel Group BSC',
                'full_name' => 'Bahrain:GHG',
                'mb_url' => '/markets/BB/stocks/GHG',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '92b0594f-d1f5-43b5-95d9-6dc32122d4d3',
            ],
            [
                'id' => '8c319bb7-b37d-4bbf-ad50-7a766c1c573d',
                'tv_id' => 'BAHRAIN-BHBX',
                'symbol' => 'BHBX',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'BHD',
                'inv_symbol' => 'BAX',
                'inv_id' => 13518,
                'name_en' => 'Bahrain All Share Index',
                'name_ar' => 'مؤشر البحرين العام',
                'description_en' => 'Bahrain All Share Index',
                'description_ar' => 'مؤشر البحرين العام',
                'short_description_en' => 'Bahrain All Share Index',
                'short_description_ar' => 'مؤشر البحرين العام',
                'full_name' => 'Bahrain :BAX',
                'mb_url' => '/markets/BB',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '',
            ],
            [
                'id' => '8dc15ebd-f59e-4474-a0d2-03b4d01994b2',
                'tv_id' => 'BAHRAIN:BEYON',
                'symbol' => 'BEYON',
                'isin' => 'BH0060713458',
                'logo_id' => 'bahrain-telecommunications',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'BEYON',
                'inv_id' => 13545,
                'name_en' => 'Bahrain Telecommunications BSC',
                'name_ar' => 'Bahrain Telecommunications BSC',
                'description_en' => 'Beyon BSC',
                'description_ar' => 'Beyon BSC',
                'short_description_en' => 'Beyon BSC',
                'short_description_ar' => 'Beyon BSC',
                'full_name' => 'Bahrain:BEYON',
                'mb_url' => '/markets/BB/stocks/BEYON',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '59049759-5928-463c-a47c-76f9aa2cf6d9',
            ],
            [
                'id' => 'bb1bb567-a582-4e49-8e35-03a9c5662c10',
                'tv_id' => 'BAHRAIN:SEEF',
                'symbol' => 'SEEF',
                'isin' => 'BH000A0M1AY7',
                'logo_id' => 'seef-properties',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'SEEF',
                'inv_id' => 13562,
                'name_en' => 'Seef Properties',
                'name_ar' => 'شركة ناس ش.م.ب',
                'description_en' => 'Seef Properties BSC',
                'description_ar' => 'Seef Properties BSC',
                'short_description_en' => 'Seef Properties BSC',
                'short_description_ar' => 'Seef Properties BSC',
                'full_name' => 'Bahrain:SEEF',
                'mb_url' => '/markets/BB/stocks/SEEF',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => 'bf0798cc-30b7-4329-84fb-6dd0ef45d5d8',
                'tv_id' => 'BAHRAIN:BASREC',
                'symbol' => 'BASREC',
                'isin' => 'BH0004659486',
                'logo_id' => 'bahrain-ship-repairing-and-engineering',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'BSRC',
                'inv_id' => 13543,
                'name_en' => 'Bahrain Ship Repairing and Engineering',
                'name_ar' => 'شركة البحرين للاتصالات السلكية واللاسلكية ش.م.ب',
                'description_en' => 'Bah. Ship Repairing&Engineering Co',
                'description_ar' => 'Bah. Ship Repairing&Engineering Co',
                'short_description_en' => 'Bah. Ship Repairing&Engineering Co',
                'short_description_ar' => 'Bah. Ship Repairing&Engineering Co',
                'full_name' => 'Bahrain:BSRC',
                'mb_url' => '/markets/BB/stocks/BASREC',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '5ac5f8ac-198b-4655-88e9-0e08c75ad038',
            ],
            [
                'id' => 'c7ab5256-1a92-4197-9889-ccd58594a535',
                'tv_id' => 'BAHRAIN:DUTYF',
                'symbol' => 'DUTYF',
                'isin' => 'BH0004656722',
                'logo_id' => 'bahrain-duty-free-shop-complex-co',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'DUTY',
                'inv_id' => 13548,
                'name_en' => 'Bahrain Duty Free Shop Complex Co',
                'name_ar' => 'شركة البحرين لتصليح السفن والهندسة ش.م.ب',
                'description_en' => 'Bahrain Duty Free Shop Complex',
                'description_ar' => 'Bahrain Duty Free Shop Complex',
                'short_description_en' => 'Bahrain Duty Free Shop Complex',
                'short_description_ar' => 'Bahrain Duty Free Shop Complex',
                'full_name' => 'Bahrain:DUTY',
                'mb_url' => '/markets/BB/stocks/DUTYF',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '0fd1bbaa-8060-4165-8084-3caf0ad624e6',
            ],
            [
                'id' => 'c8d20f61-6669-405c-b42a-0afa2178a9d6',
                'tv_id' => 'BAHRAIN:NHOTEL',
                'symbol' => 'NHOTEL',
                'isin' => 'BH0004663983',
                'logo_id' => 'national-hotels',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'NHTL',
                'inv_id' => 13559,
                'name_en' => 'National Hotels',
                'name_ar' => 'مجموعة فنادق الخليج ش.م.ب',
                'description_en' => 'National Hotels Co.',
                'description_ar' => 'National Hotels Co.',
                'short_description_en' => 'National Hotels Co.',
                'short_description_ar' => 'National Hotels Co.',
                'full_name' => 'Bahrain:NHTL',
                'mb_url' => '/markets/BB/stocks/NHOTEL',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '92b0594f-d1f5-43b5-95d9-6dc32122d4d3',
            ],
            [
                'id' => 'd82e770e-3f56-405f-a3f3-d3e2a28a23b4',
                'tv_id' => 'BAHRAIN:ESTERAD',
                'symbol' => 'ESTERAD',
                'isin' => 'BH000A0F5KU4',
                'logo_id' => 'esterad-investment',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'EICB',
                'inv_id' => 13549,
                'name_en' => 'Esterad Investment',
                'name_ar' => 'بنك انفستكورب ش.م.ب',
                'description_en' => 'Esterad Investment Company BSC',
                'description_ar' => 'Esterad Investment Company BSC',
                'short_description_en' => 'Esterad Investment Company BSC',
                'short_description_ar' => 'Esterad Investment Company BSC',
                'full_name' => 'Bahrain:EICB',
                'mb_url' => '/markets/BB/stocks/ESTERAD',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '995d8a79-659b-4672-92c2-1743f546cd9c',
            ],
            [
                'id' => 'dfa1d1cc-08fe-48d2-a7e3-4c19720c1f0d',
                'tv_id' => 'BAHRAIN:GFH',
                'symbol' => 'GFH',
                'isin' => 'BH000A0CAQK6',
                'logo_id' => 'gfh-financial-group',
                'type' => 'stock',
                'currency' => 'USD',
                'inv_symbol' => 'GFHB',
                'inv_id' => 13551,
                'name_en' => 'GFH Financial Group BSC',
                'name_ar' => 'بنك طيب ش.م.ب. (موقوف عن التداول)',
                'description_en' => 'GFH Financial Group BSC',
                'description_ar' => 'GFH Financial Group BSC',
                'short_description_en' => 'GFH Financial Group BSC',
                'short_description_ar' => 'GFH Financial Group BSC',
                'full_name' => 'Bahrain:GFHB',
                'mb_url' => '/markets/ADX/stocks/GFH',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => 'e9a66d21-2e21-4891-813d-c0b72413e608',
                'tv_id' => 'BAHRAIN:BNH',
                'symbol' => 'BNH',
                'isin' => 'BH0004658074',
                'logo_id' => 'bahrain-national-holding-co',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'BNHB',
                'inv_id' => 13541,
                'name_en' => 'Bahrain National Holding Co',
                'name_ar' => 'سوليدرتي البحرين ش.م.ب',
                'description_en' => 'Bahrain National Holding Co.',
                'description_ar' => 'Bahrain National Holding Co.',
                'short_description_en' => 'Bahrain National Holding Co.',
                'short_description_ar' => 'Bahrain National Holding Co.',
                'full_name' => 'Bahrain:BNHB',
                'mb_url' => '/markets/BB/stocks/BNH',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => 'eab8077c-fb2e-46ba-b596-b3a279f81f53',
                'tv_id' => 'BAHRAIN:CINECO',
                'symbol' => 'CINECO',
                'isin' => 'BH0004653588',
                'logo_id' => 'bahrain-cinema',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'CNCO',
                'inv_id' => 13546,
                'name_en' => 'Bahrain Cinema',
                'name_ar' => 'زين البحرين',
                'description_en' => 'Bahrain Cinema Co BSC',
                'description_ar' => 'Bahrain Cinema Co BSC',
                'short_description_en' => 'Bahrain Cinema Co BSC',
                'short_description_ar' => 'Bahrain Cinema Co BSC',
                'full_name' => 'Bahrain:CNCO',
                'mb_url' => '/markets/BB/stocks/CINECO',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '92b0594f-d1f5-43b5-95d9-6dc32122d4d3',
            ],
            [
                'id' => 'f61f576e-399d-4e3a-8ac4-2c298eabf621',
                'tv_id' => 'BAHRAIN:ALBH',
                'symbol' => 'ALBH',
                'isin' => 'BH0006000044',
                'logo_id' => 'aluminium-bahrain-bsc',
                'type' => 'stock',
                'currency' => 'BHD',
                'inv_symbol' => 'ALBH',
                'inv_id' => 40422,
                'name_en' => 'Aluminium Bahrain BSC',
                'name_ar' => 'المنيوم البحرين ش.م.ب',
                'description_en' => 'Aluminium Bahrain BSC',
                'description_ar' => 'Aluminium Bahrain BSC',
                'short_description_en' => 'Aluminium Bahrain BSC',
                'short_description_ar' => 'Aluminium Bahrain BSC',
                'full_name' => 'Bahrain:ALBH',
                'mb_url' => '/markets/BB/stocks/ALBH',
                'status' => 0,
                'country_id' => '6895eb95-0ca9-4c84-ae88-a65f8689463f',
                'market_id' => 'b1e9ae11-585e-4879-be22-7d1e34d92492',
                'sector_id' => '105189b4-0415-4156-a1a3-09266cf8f741',
            ],
        ];

        foreach ($assets as $data) {
            Asset::firstOrCreate(
                ['id' => $data['id']],
                [
                    'tv_id' => ! empty($data['tv_id']) ? $data['tv_id'] : null,
                    'symbol' => $data['symbol'],
                    'isin' => $data['isin'] ?? null,
                    'logo_id' => DB::raw('gen_random_uuid()'),
                    'type' => $data['type'],
                    'currency' => $data['currency'],
                    'inv_symbol' => $data['inv_symbol'],
                    'inv_id' => $data['inv_id'],
                    'name_en' => $data['name_en'],
                    'name_ar' => $data['name_ar'],
                    'description_en' => $data['description_en'],
                    'description_ar' => $data['description_ar'],
                    'short_description_en' => $data['short_description_en'],
                    'short_description_ar' => $data['short_description_ar'],
                    'full_name' => $data['full_name'],
                    'mb_url' => $data['mb_url'] ?? null,
                    'status' => $data['status'],
                    'country_id' => ! empty($data['country_id']) ? $data['country_id'] : null,
                    'market_id' => ! empty($data['market_id']) ? $data['market_id'] : null,
                    'sector_id' => ! empty($data['sector_id']) ? $data['sector_id'] : null,
                ]
            );
        }
    }
}
