<?php

namespace Database\Seeders;

use App\Models\Asset;
use App\Models\Market;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QatarSeeder extends Seeder
{
    /**
     * Seed the Qatar country data: market index, markets, and assets.
     */
    public function run(): void
    {
        $this->seedMarketIndices();
        $this->seedMarkets();
        $this->seedAssets();
    }

    /**
     * Seed market index assets.
     */
    private function seedMarketIndices(): void
    {
        $indices = [
            [
                'id' => '224806ca-9619-453e-8d3f-28228a83df2f', // Qatar Stock Exchange asset
                'tv_id' => 'QSE:QSI',
                'symbol' => 'QSI',
                'isin' => 'QA0000QSI',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'QSI',
                'inv_id' => 123459,
                'name_en' => 'Qatar Stock Exchange Index',
                'name_ar' => 'مؤشر بورصة قطر',
                'description_en' => 'The main index for the Qatar Stock Exchange',
                'description_ar' => 'المؤشر الرئيسي لبورصة قطر',
                'short_description_en' => 'Qatar Stock Exchange Index',
                'short_description_ar' => 'مؤشر بورصة قطر',
                'full_name' => 'Qatar:QSI',
                'mb_url' => '/markets/QE/indices/QSI',
                'status' => 1,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'sector_id' => null,
            ],
        ];

        foreach ($indices as $data) {
            Asset::firstOrCreate(
                ['id' => $data['id']],
                [
                    'tv_id' => ! empty($data['tv_id']) ? $data['tv_id'] : null,
                    'symbol' => $data['symbol'],
                    'isin' => $data['isin'] ?? null,
                    'logo_id' => DB::raw('gen_random_uuid()'),
                    'type' => $data['type'],
                    'currency' => $data['currency'],
                    'inv_symbol' => $data['inv_symbol'],
                    'inv_id' => $data['inv_id'],
                    'name_en' => $data['name_en'],
                    'name_ar' => $data['name_ar'],
                    'description_en' => $data['description_en'],
                    'description_ar' => $data['description_ar'],
                    'short_description_en' => $data['short_description_en'],
                    'short_description_ar' => $data['short_description_ar'],
                    'full_name' => $data['full_name'],
                    'mb_url' => $data['mb_url'] ?? null,
                    'status' => $data['status'],
                    'country_id' => $data['country_id'] ?? null,
                    'sector_id' => $data['sector_id'] ?? null,
                ]
            );
        }
    }

    /**
     * Seed markets.
     */
    private function seedMarkets(): void
    {
        $markets = [
            [
                'id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'name_en' => 'Qatar Stock Exchange',
                'name_ar' => 'بورصة قطر',
                'code' => 'QSE',
                'timezone' => 'Asia/Qatar',
                'is_active' => 1,
                'asset_id' => '224806ca-9619-453e-8d3f-28228a83df2f',
                'tv_link' => 'stocks-qatar',
                'trading_days' => '["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"]',
                'open_at' => '06:30:00',
                'close_at' => '10:00:00',
                'is_open' => false,
            ],
        ];

        foreach ($markets as $data) {
            Market::firstOrCreate(
                ['id' => $data['id']],
                [
                    'country_id' => $data['country_id'],
                    'name_en' => $data['name_en'],
                    'name_ar' => $data['name_ar'],
                    'code' => $data['code'],
                    'timezone' => $data['timezone'],
                    'status' => $data['is_active'],
                    'asset_id' => $data['asset_id'],
                    'tv_link' => $data['tv_link'],
                    'trading_days' => $data['trading_days'],
                    'open_at' => $data['open_at'],
                    'close_at' => $data['close_at'],
                    'is_open' => $data['is_open'],
                ]
            );
        }
    }

    /**
     * Seed stock assets.
     */
    private function seedAssets(): void
    {
        $assets = [
            [
                'id' => '07332ede-6580-4c86-adb3-0c627b0538b2',
                'tv_id' => 'QSE:QAMC',
                'symbol' => 'QAMC',
                'isin' => 'QA000M2522L9',
                'logo_id' => 'qatar-aluminium-manufacturing-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QAMC',
                'inv_id' => 1116301,
                'name_en' => 'QATAR ALUMINIUM MANUFACTURING QPSC',
                'name_ar' => 'QATAR ALUMINIUM MANUFACTURING QPSC',
                'description_en' => 'Qatar Aluminum Manufacturing Company QPSC',
                'description_ar' => 'Qatar Aluminum Manufacturing Company QPSC',
                'short_description_en' => 'Qatar Aluminum Manufacturing Company QPSC',
                'short_description_ar' => 'Qatar Aluminum Manufacturing Company QPSC',
                'full_name' => 'Doha:QAMC',
                'mb_url' => '/markets/QE/stocks/QAMC',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '105189b4-0415-4156-a1a3-09266cf8f741',
            ],
            [
                'id' => '08e4ef01-6224-4a0f-93c9-7f678862380f',
                'tv_id' => 'QSE:UDCD',
                'symbol' => 'UDCD',
                'isin' => 'QA000A0KD6M9',
                'logo_id' => 'united-development-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'UDCD',
                'inv_id' => 13225,
                'name_en' => 'UNITED DEVELOPMENT QPSC',
                'name_ar' => 'المتحدة للتنمية',
                'description_en' => 'United Development Co.',
                'description_ar' => 'United Development Co.',
                'short_description_en' => 'United Development Co.',
                'short_description_ar' => 'United Development Co.',
                'full_name' => 'Doha:UDCD',
                'mb_url' => '/markets/QE/stocks/UDCD',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '0ec30c84-eb63-40f0-b434-e8f3f14900f3',
                'tv_id' => 'QSE:QIBK',
                'symbol' => 'QIBK',
                'isin' => 'QA0006929853',
                'logo_id' => 'qatar-islamic-bank-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QISB',
                'inv_id' => 13194,
                'name_en' => 'QATAR ISLAMIC BANK QPSC',
                'name_ar' => 'المصرف',
                'description_en' => 'Qatar Islamic Bank',
                'description_ar' => 'Qatar Islamic Bank',
                'short_description_en' => 'Qatar Islamic Bank',
                'short_description_ar' => 'Qatar Islamic Bank',
                'full_name' => 'Doha:QISB',
                'mb_url' => '/markets/QE/stocks/QIBK',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '0f2ab6b5-eebb-4c8c-8dd5-6fe182b1fa50',
                'tv_id' => 'QSE:MARK',
                'symbol' => 'MARK',
                'isin' => 'QA000A0M8VM3',
                'logo_id' => 'masraf-al-rayan-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'MARK',
                'inv_id' => 13191,
                'name_en' => 'MASRAF AL RAYAN QPSC',
                'name_ar' => 'الريان',
                'description_en' => 'Masraf al rayan',
                'description_ar' => 'Masraf al rayan',
                'short_description_en' => 'Masraf al rayan',
                'short_description_ar' => 'Masraf al rayan',
                'full_name' => 'Doha:MARK',
                'mb_url' => '/markets/QE/stocks/MARK',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '0ff03936-0808-4635-8901-2c1e9e7f9940',
                'tv_id' => 'QSE:IQCD',
                'symbol' => 'IQCD',
                'isin' => 'QA000A0KD6K3',
                'logo_id' => 'industries-qatar-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'IQCD',
                'inv_id' => 13206,
                'name_en' => 'INDUSTRIES QATAR QPSC',
                'name_ar' => 'صناعات قطر',
                'description_en' => 'Industries Qatar',
                'description_ar' => 'Industries Qatar',
                'short_description_en' => 'Industries Qatar',
                'short_description_ar' => 'Industries Qatar',
                'full_name' => 'Doha:IQCD',
                'mb_url' => '/markets/QE/stocks/IQCD',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '105189b4-0415-4156-a1a3-09266cf8f741',
            ],
            [
                'id' => '12a4e926-68f5-4a28-8181-bf69c1018429',
                'tv_id' => '',
                'symbol' => 'QERI',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'QERI',
                'inv_id' => 40033,
                'name_en' => 'QE Al Rayan Islamic',
                'name_ar' => 'QE Al Rayan Islamic',
                'description_en' => 'QE Al Rayan Islamic',
                'description_ar' => 'QE Al Rayan Islamic',
                'short_description_en' => 'QE Al Rayan Islamic',
                'short_description_ar' => 'QE Al Rayan Islamic',
                'full_name' => 'Doha:QERI',
                'mb_url' => '',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '',
            ],
            [
                'id' => '1ac5d2a6-f825-4679-acf2-547e2c191394',
                'tv_id' => 'QSE:DOHI',
                'symbol' => 'DOHI',
                'isin' => 'QA0007227794',
                'logo_id' => 'doha-insurance-group-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'DICO',
                'inv_id' => 13202,
                'name_en' => 'DOHA INSURANCE GROUP QPSC',
                'name_ar' => 'الدوحة',
                'description_en' => 'Doha Insurance',
                'description_ar' => 'Doha Insurance',
                'short_description_en' => 'Doha Insurance',
                'short_description_ar' => 'Doha Insurance',
                'full_name' => 'Doha:DICO',
                'mb_url' => '/markets/QE/stocks/DOHI',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '1e40fe02-28dd-45aa-99d6-5d1fb056bf29',
                'tv_id' => '',
                'symbol' => 'QETR',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'QETR',
                'inv_id' => 40036,
                'name_en' => 'QE Total Return',
                'name_ar' => 'QE Total Return',
                'description_en' => 'QE Total Return',
                'description_ar' => 'QE Total Return',
                'short_description_en' => 'QE Total Return',
                'short_description_ar' => 'QE Total Return',
                'full_name' => 'Doha:QETR',
                'mb_url' => '',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '',
            ],
            [
                'id' => '22ee32fd-6283-41ac-8489-3a8eb09d99b6',
                'tv_id' => 'QSE:MPHC',
                'symbol' => 'MPHC',
                'isin' => 'QA000VSUG130',
                'logo_id' => 'mesaieed-petrochemical-holding-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'MPHC',
                'inv_id' => 945817,
                'name_en' => 'MESAIEED PETROCHEMICAL HOLDING QPSC',
                'name_ar' => 'مسيعيد',
                'description_en' => 'Mesaieed Petrochemical Holding',
                'description_ar' => 'Mesaieed Petrochemical Holding',
                'short_description_en' => 'Mesaieed Petrochemical Holding',
                'short_description_ar' => 'Mesaieed Petrochemical Holding',
                'full_name' => 'Doha:MPHC',
                'mb_url' => '/markets/QE/stocks/MPHC',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '5ac5f8ac-198b-4655-88e9-0e08c75ad038',
            ],
            [
                'id' => '22f02a92-a81c-4e0b-9522-7266a1f4996a',
                'tv_id' => 'QSE:AHCS',
                'symbol' => 'AHCS',
                'isin' => 'QA000A0NCQB1',
                'logo_id' => 'aamal-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'AHCS',
                'inv_id' => 13196,
                'name_en' => 'AAMAL QPSC',
                'name_ar' => 'أعمال',
                'description_en' => 'Aamal',
                'description_ar' => 'Aamal',
                'short_description_en' => 'Aamal',
                'short_description_ar' => 'Aamal',
                'full_name' => 'Doha:AHCS',
                'mb_url' => '/markets/QE/stocks/AHCS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '0fd1bbaa-8060-4165-8084-3caf0ad624e6',
            ],
            [
                'id' => '2a176a34-c081-4a5f-9000-9d29fb42df72',
                'tv_id' => 'QSE:GISS',
                'symbol' => 'GISS',
                'isin' => 'QA000A0Q6LH4',
                'logo_id' => 'gulf-international-services-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'GISS',
                'inv_id' => 13204,
                'name_en' => 'GULF INTERNATIONAL SERVICES QPSC',
                'name_ar' => 'الخليج الدولية',
                'description_en' => 'Gulf International',
                'description_ar' => 'Gulf International',
                'short_description_en' => 'Gulf International',
                'short_description_ar' => 'Gulf International',
                'full_name' => 'Doha:GISS',
                'mb_url' => '/markets/QE/stocks/GISS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '12755d84-04b8-4c5d-844b-4de9a1c763c7',
            ],
            [
                'id' => '2af69104-fac3-4d7f-b225-c64d5ccab81e',
                'tv_id' => 'QSE:NLCS',
                'symbol' => 'NLCS',
                'isin' => 'QA000A0KD6Q0',
                'logo_id' => 'national-leasing-holding-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'NLCS',
                'inv_id' => 13210,
                'name_en' => 'NATIONAL LEASING HOLDING QPSC',
                'name_ar' => 'الاجارة',
                'description_en' => 'Alijarah Holding Co QPSC',
                'description_ar' => 'Alijarah Holding Co QPSC',
                'short_description_en' => 'Alijarah Holding Co QPSC',
                'short_description_ar' => 'Alijarah Holding Co QPSC',
                'full_name' => 'Doha:NLCS',
                'mb_url' => '/markets/QE/stocks/NLCS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '2b0f4360-8ae0-4f29-a019-8e03d6b46610',
                'tv_id' => 'QSE:MCCS',
                'symbol' => 'MCCS',
                'isin' => 'QA000A0NBGK5',
                'logo_id' => 'mannai-corporation-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'MCCS',
                'inv_id' => 13208,
                'name_en' => 'MANNAI CORPORATION QPSC',
                'name_ar' => 'مجمع المناعي',
                'description_en' => 'Mannai Corp.',
                'description_ar' => 'Mannai Corp.',
                'short_description_en' => 'Mannai Corp.',
                'short_description_ar' => 'Mannai Corp.',
                'full_name' => 'Doha:MCCS',
                'mb_url' => '/markets/QE/stocks/MCCS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '47ebe274-48d3-433d-b4ab-32fd748bd8ad',
            ],
            [
                'id' => '34a199a1-7d28-4d40-b451-803fb67d20ba',
                'tv_id' => 'QSE:QIIK',
                'symbol' => 'QIIK',
                'isin' => 'QA0006929879',
                'logo_id' => 'qatar-international-islamic-bank-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QIIB',
                'inv_id' => 13193,
                'name_en' => 'QATAR INTERNATIONAL ISLAMIC BANK QPSC',
                'name_ar' => 'الدولي',
                'description_en' => 'Qatar International Islamic Bank',
                'description_ar' => 'Qatar International Islamic Bank',
                'short_description_en' => 'Qatar International Islamic Bank',
                'short_description_ar' => 'Qatar International Islamic Bank',
                'full_name' => 'Doha:QIIB',
                'mb_url' => '/markets/QE/stocks/QIIK',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '35b1c208-cd42-4347-8a5a-8d6d5293f4ab',
                'tv_id' => 'QSE:TQES',
                'symbol' => 'TQES',
                'isin' => 'QA0004J80UC0',
                'logo_id' => 'qatar-electronic-systems-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'TQES',
                'inv_id' => 1217523,
                'name_en' => 'QATAR ELECTRONIC SYSTEMS QPSC',
                'name_ar' => 'QATAR ELECTRONIC SYSTEMS QPSC',
                'description_en' => 'Qatar Electronic Systems Company',
                'description_ar' => 'Qatar Electronic Systems Company',
                'short_description_en' => 'Qatar Electronic Systems Company',
                'short_description_ar' => 'Qatar Electronic Systems Company',
                'full_name' => 'Doha:TQES',
                'mb_url' => '/markets/QE/stocks/TQES',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '92b0594f-d1f5-43b5-95d9-6dc32122d4d3',
            ],
            [
                'id' => '36550fac-471a-4cf1-96c0-840406c98629',
                'tv_id' => 'QSE:MCGS',
                'symbol' => 'MCGS',
                'isin' => 'QA0006929754',
                'logo_id' => 'medicare-group-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'MCGS',
                'inv_id' => 13209,
                'name_en' => 'MEDICARE GROUP QPSC',
                'name_ar' => 'الرعاية',
                'description_en' => 'Medicare',
                'description_ar' => 'Medicare',
                'short_description_en' => 'Medicare',
                'short_description_ar' => 'Medicare',
                'full_name' => 'Doha:MCGS',
                'mb_url' => '/markets/QE/stocks/MCGS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '8d509fc2-bfab-4da4-973c-81e35e0a7aa2',
            ],
            [
                'id' => '3d54510b-37df-4701-8e70-ccfe2f8ee9bf',
                'tv_id' => 'QSE:ERES',
                'symbol' => 'ERES',
                'isin' => 'QA000A0NE8B4',
                'logo_id' => 'ezdan-holding-group-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'ERES',
                'inv_id' => 13203,
                'name_en' => 'EZDAN HOLDING GROUP QPSC',
                'name_ar' => 'إزدان القابضة',
                'description_en' => 'Ezdan',
                'description_ar' => 'Ezdan',
                'short_description_en' => 'Ezdan',
                'short_description_ar' => 'Ezdan',
                'full_name' => 'Doha:ERES',
                'mb_url' => '/markets/QE/stocks/ERES',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '40c05ced-79df-4ea0-8c7f-00389936f8ed',
                'tv_id' => 'QSE:GWCS',
                'symbol' => 'GWCS',
                'isin' => 'QA000A0KD6H9',
                'logo_id' => 'gulf-warehousing-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'GWCS',
                'inv_id' => 13205,
                'name_en' => 'GULF WAREHOUSING QPSC',
                'name_ar' => 'مخازن',
                'description_en' => 'Gulf warehousing Co',
                'description_ar' => 'Gulf warehousing Co',
                'short_description_en' => 'Gulf warehousing Co',
                'short_description_ar' => 'Gulf warehousing Co',
                'full_name' => 'Doha:GWCS',
                'mb_url' => '/markets/QE/stocks/GWCS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '8bd6ab2c-b1cf-4258-8b1c-82f9445d5c04',
            ],
            [
                'id' => '424936c6-422f-46e5-8099-989f13c7082c',
                'tv_id' => 'QSE:AKHI',
                'symbol' => 'AKHI',
                'isin' => 'QA0006929762',
                'logo_id' => 'al-khaleej-takaful-insurance-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'KINS',
                'inv_id' => 13197,
                'name_en' => 'AL KHALEEJ TAKAFUL INSURANCE QPSC',
                'name_ar' => 'الخليج التكافلي',
                'description_en' => 'Al Kaleej Takaful',
                'description_ar' => 'Al Kaleej Takaful',
                'short_description_en' => 'Al Kaleej Takaful',
                'short_description_ar' => 'Al Kaleej Takaful',
                'full_name' => 'Doha:KINS',
                'mb_url' => '/markets/QE/stocks/AKHI',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '44cb2b37-afbb-472f-ac16-c6573024c482',
                'tv_id' => 'QSE:VFQS',
                'symbol' => 'VFQS',
                'isin' => 'QA000A0Q5NE9',
                'logo_id' => 'vodafone',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'VFQS',
                'inv_id' => 13226,
                'name_en' => 'VODAFONE QATAR PQSC',
                'name_ar' => 'فودافون قطر',
                'description_en' => 'Vodafone Qatar',
                'description_ar' => 'Vodafone Qatar',
                'short_description_en' => 'Vodafone Qatar',
                'short_description_ar' => 'Vodafone Qatar',
                'full_name' => 'Doha:VFQS',
                'mb_url' => '/markets/QE/stocks/VFQS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '59049759-5928-463c-a47c-76f9aa2cf6d9',
            ],
            [
                'id' => '450e32a0-c98d-4687-b8aa-139e422297d8',
                'tv_id' => 'QSE:MKDM',
                'symbol' => 'MKDM',
                'isin' => 'QA000BD0VCK4',
                'logo_id' => 'mekdam-holding-group-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'MKDM',
                'inv_id' => 1180465,
                'name_en' => 'MEKDAM HOLDING GROUP QPSC',
                'name_ar' => 'MEKDAM HOLDING GROUP QPSC',
                'description_en' => 'Mekdam Holding Group QPSC',
                'description_ar' => 'Mekdam Holding Group QPSC',
                'short_description_en' => 'Mekdam Holding Group QPSC',
                'short_description_ar' => 'Mekdam Holding Group QPSC',
                'full_name' => 'Doha:MKDM',
                'mb_url' => '/markets/QE/stocks/MKDM',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '5ac5f8ac-198b-4655-88e9-0e08c75ad038',
            ],
            [
                'id' => '537f1fdd-4a41-4c7b-a831-1bf723fff2aa',
                'tv_id' => '',
                'symbol' => 'QECON',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'QECON',
                'inv_id' => 40031,
                'name_en' => 'QE Consumer Goods & Services',
                'name_ar' => 'QE Consumer Goods & Services',
                'description_en' => 'QE Consumer Goods & Services',
                'description_ar' => 'QE Consumer Goods & Services',
                'short_description_en' => 'QE Consumer Goods & Services',
                'short_description_ar' => 'QE Consumer Goods & Services',
                'full_name' => 'Doha:QECON',
                'mb_url' => '',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '',
            ],
            [
                'id' => '562bb784-de37-48b1-a1ab-90faa9fc5103',
                'tv_id' => 'QSE:QIGD',
                'symbol' => 'QIGD',
                'isin' => 'QA000A0NA0T7',
                'logo_id' => 'qatari-investors-group-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QIGD',
                'inv_id' => 13199,
                'name_en' => 'QATARI INVESTORS GROUP QPSC',
                'name_ar' => 'المستثمرين',
                'description_en' => 'Qatari Investors Group QPSC',
                'description_ar' => 'Qatari Investors Group QPSC',
                'short_description_en' => 'Qatari Investors Group QPSC',
                'short_description_ar' => 'Qatari Investors Group QPSC',
                'full_name' => 'Doha:QIGD',
                'mb_url' => '/markets/QE/stocks/QIGD',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '105189b4-0415-4156-a1a3-09266cf8f741',
            ],
            [
                'id' => '5ab024a3-8799-4728-817f-3627abb50e70',
                'tv_id' => 'QSE:WDAM',
                'symbol' => 'WDAM',
                'isin' => 'QA000A0KD6N7',
                'logo_id' => 'widam-food-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'WDAM',
                'inv_id' => 13217,
                'name_en' => 'WIDAM FOOD QPSC',
                'name_ar' => 'ودام',
                'description_en' => 'Widam Food',
                'description_ar' => 'Widam Food',
                'short_description_en' => 'Widam Food',
                'short_description_ar' => 'Widam Food',
                'full_name' => 'Doha:WDAM',
                'mb_url' => '/markets/QE/stocks/WDAM',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '0fd1bbaa-8060-4165-8084-3caf0ad624e6',
            ],
            [
                'id' => '5f0fe9e7-df80-49c1-9319-cf4b96e29439',
                'tv_id' => 'QSE:BRES',
                'symbol' => 'BRES',
                'isin' => 'QA000A0KD6J5',
                'logo_id' => 'barwa-real-estate-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'BRES',
                'inv_id' => 13200,
                'name_en' => 'BARWA REAL ESTATE QPSC',
                'name_ar' => 'بروة',
                'description_en' => 'Barwa',
                'description_ar' => 'Barwa',
                'short_description_en' => 'Barwa',
                'short_description_ar' => 'Barwa',
                'full_name' => 'Doha:BRES',
                'mb_url' => '/markets/QE/stocks/BRES',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '5fa143d5-e0b0-434b-9d52-5d7447544263',
                'tv_id' => 'QSE:BLDN',
                'symbol' => 'BLDN',
                'isin' => 'QA000T98R9J4',
                'logo_id' => 'baladna-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'BLDN',
                'inv_id' => 1156660,
                'name_en' => 'BALADNA QPSC',
                'name_ar' => 'BALADNA QPSC',
                'description_en' => 'Baladna Food Industries Co',
                'description_ar' => 'Baladna Food Industries Co',
                'short_description_en' => 'Baladna Food Industries Co',
                'short_description_ar' => 'Baladna Food Industries Co',
                'full_name' => 'Doha:BLDN',
                'mb_url' => '/markets/QE/stocks/BLDN',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '5ac5f8ac-198b-4655-88e9-0e08c75ad038',
            ],
            [
                'id' => '657f2e0f-9f4d-403e-96e4-615f63a0e5cf',
                'tv_id' => 'QSE:QEWS',
                'symbol' => 'QEWS',
                'isin' => 'QA0006929812',
                'logo_id' => 'qatar-electricity-and-water-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QEWC',
                'inv_id' => 13212,
                'name_en' => 'QATAR ELECTRICITY AND WATER QPSC',
                'name_ar' => 'كهرباء وماء',
                'description_en' => 'Qatar Electricity and Water',
                'description_ar' => 'Qatar Electricity and Water',
                'short_description_en' => 'Qatar Electricity and Water',
                'short_description_ar' => 'Qatar Electricity and Water',
                'full_name' => 'Doha:QEWC',
                'mb_url' => '/markets/QE/stocks/QEWS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'e7fa345f-7eea-4617-b205-0e821a1dc7f5',
            ],
            [
                'id' => '69805fdd-5b05-4acd-b621-801dce6b493b',
                'tv_id' => 'QSE:QFLS',
                'symbol' => 'QFLS',
                'isin' => 'QA0001200771',
                'logo_id' => 'qatar-fuel-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QFLS',
                'inv_id' => 13221,
                'name_en' => 'QATAR FUEL QPSC',
                'name_ar' => 'قطر للوقود',
                'description_en' => 'Qatar Fuel',
                'description_ar' => 'Qatar Fuel',
                'short_description_en' => 'Qatar Fuel',
                'short_description_ar' => 'Qatar Fuel',
                'full_name' => 'Doha:QFLS',
                'mb_url' => '/markets/QE/stocks/QFLS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '12755d84-04b8-4c5d-844b-4de9a1c763c7',
            ],
            [
                'id' => '6a7234b4-5c74-4888-b0bb-1735b9598887',
                'tv_id' => 'QSE:SIIS',
                'symbol' => 'SIIS',
                'isin' => 'QA0007227745',
                'logo_id' => 'salam-international-investment-limited-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'SALM',
                'inv_id' => 13224,
                'name_en' => 'SALAM INTERNATIONAL INVESTMENT LIMITED QPSC',
                'name_ar' => 'السلام',
                'description_en' => 'Salam International',
                'description_ar' => 'Salam International',
                'short_description_en' => 'Salam International',
                'short_description_ar' => 'Salam International',
                'full_name' => 'Doha:SALM',
                'mb_url' => '/markets/QE/stocks/SIIS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '0fd1bbaa-8060-4165-8084-3caf0ad624e6',
            ],
            [
                'id' => '6a8d143a-7529-42c1-8c72-a4801a675a5d',
                'tv_id' => 'QSE:QNBK',
                'symbol' => 'QNBK',
                'isin' => 'QA0006929895',
                'logo_id' => 'qatar-national-bank-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QNBK',
                'inv_id' => 13195,
                'name_en' => 'QATAR NATIONAL BANK QPSC',
                'name_ar' => 'بنك قطر الدولي',
                'description_en' => 'QNB',
                'description_ar' => 'QNB',
                'short_description_en' => 'QNB',
                'short_description_ar' => 'QNB',
                'full_name' => 'Doha:QNBK',
                'mb_url' => '/markets/QE/stocks/QNBK',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '6cb51261-54e0-4c50-a0dc-b51a29e1d713',
                'tv_id' => 'QSE:QGRI',
                'symbol' => 'QGRI',
                'isin' => 'QA0006929820',
                'logo_id' => 'qatar-general-insurance-and-reinsurance-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QGIR',
                'inv_id' => 13214,
                'name_en' => 'QATAR GENERAL INSURANCE AND REINSURANCE QPSC',
                'name_ar' => 'العامة',
                'description_en' => 'General Insurance & Reinsurance Co',
                'description_ar' => 'General Insurance & Reinsurance Co',
                'short_description_en' => 'General Insurance & Reinsurance Co',
                'short_description_ar' => 'General Insurance & Reinsurance Co',
                'full_name' => 'Doha:QGIR',
                'mb_url' => '/markets/QE/stocks/QGRI',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '6fdc421b-8733-434e-95d8-ec700f97c739',
                'tv_id' => '',
                'symbol' => 'FTDQAT',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'FTDQAT',
                'inv_id' => 28894,
                'name_en' => 'FTSE NASDAQ Qatar 10',
                'name_ar' => 'FTSE NASDAQ Qatar 10',
                'description_en' => 'FTSE NASDAQ Qatar 10',
                'description_ar' => 'FTSE NASDAQ Qatar 10',
                'short_description_en' => 'FTSE NASDAQ Qatar 10',
                'short_description_ar' => 'FTSE NASDAQ Qatar 10',
                'full_name' => 'Doha:FTDQAT',
                'mb_url' => '',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '',
            ],
            [
                'id' => '80c30b8e-10cd-4dc7-aa85-481624f19c99',
                'tv_id' => 'QSE:QATI',
                'symbol' => 'QATI',
                'isin' => 'QA0006929838',
                'logo_id' => 'qatar-insurance-qspc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QINS',
                'inv_id' => 13568,
                'name_en' => 'QATAR INSURANCE QSPC',
                'name_ar' => 'قطر',
                'description_en' => 'Qatar Insurance Co.',
                'description_ar' => 'Qatar Insurance Co.',
                'short_description_en' => 'Qatar Insurance Co.',
                'short_description_ar' => 'Qatar Insurance Co.',
                'full_name' => 'Doha:QINS',
                'mb_url' => '/markets/QE/stocks/QATI',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '8440fd32-825a-4b3f-bca7-56fb3d29714c',
                'tv_id' => 'QSE:QLMI',
                'symbol' => 'QLMI',
                'isin' => 'QA000QLM0003',
                'logo_id' => 'qlm-life-and-medical-insurance-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QLMI',
                'inv_id' => 1171236,
                'name_en' => 'QLM LIFE AND MEDICAL INSURANCE QPSC',
                'name_ar' => 'QLM LIFE AND MEDICAL INSURANCE QPSC',
                'description_en' => 'QLM Life & Medical Insurance Company WLL',
                'description_ar' => 'QLM Life & Medical Insurance Company WLL',
                'short_description_en' => 'QLM Life & Medical Insurance Company WLL',
                'short_description_ar' => 'QLM Life & Medical Insurance Company WLL',
                'full_name' => 'Doha:QLMI',
                'mb_url' => '/markets/QE/stocks/QLMI',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '869bf026-aeb3-4e35-921d-712a5d124c7a',
                'tv_id' => 'QSE:BEMA',
                'symbol' => 'BEMA',
                'isin' => 'QA000LB5T4U2',
                'logo_id' => 'damaan-islamic-insurance-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'BEMA',
                'inv_id' => 1199580,
                'name_en' => 'DAMAAN ISLAMIC INSURANCE QPSC',
                'name_ar' => 'DAMAAN ISLAMIC INSURANCE QPSC',
                'description_en' => 'Damaan Islamic Insurance Co Beema',
                'description_ar' => 'Damaan Islamic Insurance Co Beema',
                'short_description_en' => 'Damaan Islamic Insurance Co Beema',
                'short_description_ar' => 'Damaan Islamic Insurance Co Beema',
                'full_name' => 'Doha:BEMA',
                'mb_url' => '/markets/QE/stocks/BEMA',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '8986aa2d-3cfd-4fb3-9250-59b6fcee2e55',
                'tv_id' => 'QSE:QNNS',
                'symbol' => 'QNNS',
                'isin' => 'QA0007227695',
                'logo_id' => 'qatar-navigation-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QNNC',
                'inv_id' => 13222,
                'name_en' => 'QATAR NAVIGATION QPSC',
                'name_ar' => 'الملاحة',
                'description_en' => 'Qatar Navigation',
                'description_ar' => 'Qatar Navigation',
                'short_description_en' => 'Qatar Navigation',
                'short_description_ar' => 'Qatar Navigation',
                'full_name' => 'Doha:QNNC',
                'mb_url' => '/markets/QE/stocks/QNNS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '8bd6ab2c-b1cf-4258-8b1c-82f9445d5c04',
            ],
            [
                'id' => '8a0a55ec-9fc4-4049-922b-6e66283d8196',
                'tv_id' => 'QSE:IHGS',
                'symbol' => 'IHGS',
                'isin' => 'QA000A1C6VS5',
                'logo_id' => 'inma-holding-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'IHGS',
                'inv_id' => 13207,
                'name_en' => 'INMA HOLDING QPSC',
                'name_ar' => 'الإسلامية القابضة',
                'description_en' => 'Inma Holding Co',
                'description_ar' => 'Inma Holding Co',
                'short_description_en' => 'Inma Holding Co',
                'short_description_ar' => 'Inma Holding Co',
                'full_name' => 'Doha:IHGS',
                'mb_url' => '/markets/QE/stocks/IHGS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '93919d13-87da-4e70-b37a-b0cf7891c0ef',
                'tv_id' => 'QSE:MEZA',
                'symbol' => 'MEZA',
                'isin' => 'QA000PK2KD10',
                'logo_id' => 'meeza-qstp-llc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'MEZA',
                'inv_id' => 1206059,
                'name_en' => 'MEEZA QSTP LLC',
                'name_ar' => 'MEEZA QSTP LLC',
                'description_en' => 'Meeza Qstp LLC',
                'description_ar' => 'Meeza Qstp LLC',
                'short_description_en' => 'Meeza Qstp LLC',
                'short_description_ar' => 'Meeza Qstp LLC',
                'full_name' => 'Doha:MEZA',
                'mb_url' => '/markets/QE/stocks/MEZA',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '47ebe274-48d3-433d-b4ab-32fd748bd8ad',
            ],
            [
                'id' => '978edd98-d618-49b7-9182-75948b226c38',
                'tv_id' => 'QSE:QGMD',
                'symbol' => 'QGMD',
                'isin' => 'QA0001200763',
                'logo_id' => 'qatari-german-for-medical-devices-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QGMS',
                'inv_id' => 13220,
                'name_en' => 'QATARI GERMAN FOR MEDICAL DEVICES QPSC',
                'name_ar' => 'الطبية',
                'description_en' => 'Qatar German Company for Medical Devices',
                'description_ar' => 'Qatar German Company for Medical Devices',
                'short_description_en' => 'Qatar German Company for Medical Devices',
                'short_description_ar' => 'Qatar German Company for Medical Devices',
                'full_name' => 'Doha:QGMS',
                'mb_url' => '/markets/QE/stocks/QGMD',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '0fd1bbaa-8060-4165-8084-3caf0ad624e6',
            ],
            [
                'id' => '9b4825bf-5d83-4eb0-a6cd-1a362e8f1864',
                'tv_id' => 'QSE:ZHCD',
                'symbol' => 'ZHCD',
                'isin' => 'QA0006929788',
                'logo_id' => 'zad-holding-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'ZHCD',
                'inv_id' => 13227,
                'name_en' => 'ZAD HOLDING QPSC',
                'name_ar' => 'زاد',
                'description_en' => 'Zad Holding Company',
                'description_ar' => 'Zad Holding Company',
                'short_description_en' => 'Zad Holding Company',
                'short_description_ar' => 'Zad Holding Company',
                'full_name' => 'Doha:ZHCD',
                'mb_url' => '/markets/QE/stocks/ZHCD',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '5cba38be-1950-4fcd-8f78-57911ef2b71e',
            ],
            [
                'id' => '9c12baf7-9b87-458a-a624-66d30e85c649',
                'tv_id' => 'QSE:QISI',
                'symbol' => 'QISI',
                'isin' => 'QA0006929861',
                'logo_id' => 'qatar-islamic-insurance-group-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QIIC',
                'inv_id' => 13216,
                'name_en' => 'QATAR ISLAMIC INSURANCE GROUP QPSC',
                'name_ar' => 'الاسلامية',
                'description_en' => 'Qatar Islamic Insurance Company',
                'description_ar' => 'Qatar Islamic Insurance Company',
                'short_description_en' => 'Qatar Islamic Insurance Company',
                'short_description_ar' => 'Qatar Islamic Insurance Company',
                'full_name' => 'Doha:QIIC',
                'mb_url' => '/markets/QE/stocks/QISI',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => '9d54cbdc-1f4d-402d-8942-e03d92409103',
                'tv_id' => '',
                'symbol' => 'QEINS',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'QEINS',
                'inv_id' => 13184,
                'name_en' => 'Insurance',
                'name_ar' => 'Insurance',
                'description_en' => 'Insurance',
                'description_ar' => 'Insurance',
                'short_description_en' => 'Insurance',
                'short_description_ar' => 'Insurance',
                'full_name' => 'Doha:QEINS',
                'mb_url' => '',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '',
            ],
            [
                'id' => '9d59d318-fdc4-4b65-90e4-a220ce4a89c0',
                'tv_id' => '',
                'symbol' => 'QETLC',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'QETLC',
                'inv_id' => 40039,
                'name_en' => 'QE Telecoms',
                'name_ar' => 'QE Telecoms',
                'description_en' => 'QE Telecoms',
                'description_ar' => 'QE Telecoms',
                'short_description_en' => 'QE Telecoms',
                'short_description_ar' => 'QE Telecoms',
                'full_name' => 'Doha:QETLC',
                'mb_url' => '',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '',
            ],
            [
                'id' => '9e47f817-620f-4d41-8375-211d80415f6c',
                'tv_id' => 'QSE:DBIS',
                'symbol' => 'DBIS',
                'isin' => 'QA000A0KD6P2',
                'logo_id' => 'dlala-brokerage-and-investment-holding-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'DBIS',
                'inv_id' => 13201,
                'name_en' => 'DLALA BROKERAGE AND INVESTMENT HOLDING QPSC',
                'name_ar' => 'دلالة',
                'description_en' => 'Dlala',
                'description_ar' => 'Dlala',
                'short_description_en' => 'Dlala',
                'short_description_ar' => 'Dlala',
                'full_name' => 'Doha:DBIS',
                'mb_url' => '/markets/QE/stocks/DBIS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => 'a357bd16-ee8c-4983-9a58-a59fd8643aef',
                'tv_id' => 'QSE:QOIS',
                'symbol' => 'QOIS',
                'isin' => 'QA000A0NCQA3',
                'logo_id' => 'qatar-oman-investment-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QOIS',
                'inv_id' => 13223,
                'name_en' => 'QATAR OMAN INVESTMENT QPSC',
                'name_ar' => 'قطروعمان',
                'description_en' => 'Qatar Oman Investment Company',
                'description_ar' => 'Qatar Oman Investment Company',
                'short_description_en' => 'Qatar Oman Investment Company',
                'short_description_ar' => 'Qatar Oman Investment Company',
                'full_name' => 'Doha:QOIS',
                'mb_url' => '/markets/QE/stocks/QOIS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => 'ae2d2880-0090-4a67-bdd7-9cc66f211faa',
                'tv_id' => '',
                'symbol' => 'QEAS',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'QEAS',
                'inv_id' => 40038,
                'name_en' => 'QE All Shares',
                'name_ar' => 'QE All Shares',
                'description_en' => 'QE All Shares',
                'description_ar' => 'QE All Shares',
                'short_description_en' => 'QE All Shares',
                'short_description_ar' => 'QE All Shares',
                'full_name' => 'Doha:QEAS',
                'mb_url' => '',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '',
            ],
            [
                'id' => 'b08a4060-b216-48e3-96c7-d1e054769b2f',
                'tv_id' => 'QSE:FALH',
                'symbol' => 'FALH',
                'isin' => 'QA0006H60SJ0',
                'logo_id' => 'al-faleh-educational-holding-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'FALH',
                'inv_id' => 1173539,
                'name_en' => 'AL FALEH EDUCATIONAL HOLDING QPSC',
                'name_ar' => 'AL FALEH EDUCATIONAL HOLDING QPSC',
                'description_en' => 'Al Faleh Educational Holding Company Q.P.S.C',
                'description_ar' => 'Al Faleh Educational Holding Company Q.P.S.C',
                'short_description_en' => 'Al Faleh Educational Holding Company Q.P.S.C',
                'short_description_ar' => 'Al Faleh Educational Holding Company Q.P.S.C',
                'full_name' => 'Doha:FALH',
                'mb_url' => '/markets/QE/stocks/FALH',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '5ac5f8ac-198b-4655-88e9-0e08c75ad038',
            ],
            [
                'id' => 'b5d228f7-77db-402b-b30e-430d42723a05',
                'tv_id' => '',
                'symbol' => 'QEREA',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'QEREA',
                'inv_id' => 40037,
                'name_en' => 'QE Real Estate',
                'name_ar' => 'QE Real Estate',
                'description_en' => 'QE Real Estate',
                'description_ar' => 'QE Real Estate',
                'short_description_en' => 'QE Real Estate',
                'short_description_ar' => 'QE Real Estate',
                'full_name' => 'Doha:QEREA',
                'mb_url' => '',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '',
            ],
            [
                'id' => 'bb77f35c-64df-41b6-9a87-25a1f7c94d95',
                'tv_id' => 'QSE:ABQK',
                'symbol' => 'ABQK',
                'isin' => 'QA0001200748',
                'logo_id' => 'ahli-bank-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'AABQ',
                'inv_id' => 13187,
                'name_en' => 'AHLI BANK QPSC',
                'name_ar' => 'الاهلي',
                'description_en' => 'Al Ahli Bank',
                'description_ar' => 'Al Ahli Bank',
                'short_description_en' => 'Al Ahli Bank',
                'short_description_ar' => 'Al Ahli Bank',
                'full_name' => 'Doha:AABQ',
                'mb_url' => '/markets/QE/stocks/ABQK',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => 'c0dc0a02-5e03-4339-a728-48c6ef97c221',
                'tv_id' => 'QSE:MERS',
                'symbol' => 'MERS',
                'isin' => 'QA000A0YDSW8',
                'logo_id' => 'al-meera-consumer-goods-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'MERS',
                'inv_id' => 13198,
                'name_en' => 'AL MEERA CONSUMER GOODS QPSC',
                'name_ar' => 'الميرة',
                'description_en' => 'Al Meera',
                'description_ar' => 'Al Meera',
                'short_description_en' => 'Al Meera',
                'short_description_ar' => 'Al Meera',
                'full_name' => 'Doha:MERS',
                'mb_url' => '/markets/QE/stocks/MERS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '0fd1bbaa-8060-4165-8084-3caf0ad624e6',
            ],
            [
                'id' => 'c4e5a613-d69f-4a93-9266-64189b3480a1',
                'tv_id' => 'QSE:CBQK',
                'symbol' => 'CBQK',
                'isin' => 'QA0007227752',
                'logo_id' => 'the-commercial-bank-psqc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'COMB',
                'inv_id' => 13192,
                'name_en' => 'THE COMMERCIAL BANK PSQC',
                'name_ar' => 'التجاري',
                'description_en' => 'Commercial Bank of Qatar',
                'description_ar' => 'Commercial Bank of Qatar',
                'short_description_en' => 'Commercial Bank of Qatar',
                'short_description_ar' => 'Commercial Bank of Qatar',
                'full_name' => 'Doha:COMB',
                'mb_url' => '/markets/QE/stocks/CBQK',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => 'c5938b31-5d17-4768-a505-57fd342ea973',
                'tv_id' => 'QSE:QGTS',
                'symbol' => 'QGTS',
                'isin' => 'QA000A0KD6L1',
                'logo_id' => 'qatar-gas-transport-ltd-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QGTS',
                'inv_id' => 13213,
                'name_en' => 'QATAR GAS TRANSPORT LTD QPSC',
                'name_ar' => 'ناقلات',
                'description_en' => 'Qatar Gas Transport Company',
                'description_ar' => 'Qatar Gas Transport Company',
                'short_description_en' => 'Qatar Gas Transport Company',
                'short_description_ar' => 'Qatar Gas Transport Company',
                'full_name' => 'Doha:QGTS',
                'mb_url' => '/markets/QE/stocks/QGTS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '8bd6ab2c-b1cf-4258-8b1c-82f9445d5c04',
            ],
            [
                'id' => 'c7d41dad-0399-4863-a9aa-605a899a73c6',
                'tv_id' => '',
                'symbol' => 'QEIND',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'QEIND',
                'inv_id' => 13183,
                'name_en' => 'Industry',
                'name_ar' => 'Industry',
                'description_en' => 'Industry',
                'description_ar' => 'Industry',
                'short_description_en' => 'Industry',
                'short_description_ar' => 'Industry',
                'full_name' => 'Doha:QEIND',
                'mb_url' => '',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '',
            ],
            [
                'id' => 'cf3a28cb-4257-411b-b9a3-fd1c29f2735e',
                'tv_id' => 'QSE:QCFS',
                'symbol' => 'QCFS',
                'isin' => 'QA0006929796',
                'logo_id' => 'qatar-cinema-and-film-distribution-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QCFD',
                'inv_id' => 13211,
                'name_en' => 'QATAR CINEMA AND FILM DISTRIBUTION QPSC',
                'name_ar' => 'السينما',
                'description_en' => 'Qatar Cinema & Film Distribution',
                'description_ar' => 'Qatar Cinema & Film Distribution',
                'short_description_en' => 'Qatar Cinema & Film Distribution',
                'short_description_ar' => 'Qatar Cinema & Film Distribution',
                'full_name' => 'Doha:QCFD',
                'mb_url' => '/markets/QE/stocks/QCFS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '92b0594f-d1f5-43b5-95d9-6dc32122d4d3',
            ],
            [
                'id' => 'd5c7a13c-b6e5-4b58-8e31-c2c5d1607b84',
                'tv_id' => '',
                'symbol' => 'QETRN',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'QETRN',
                'inv_id' => 40035,
                'name_en' => 'QE Transportation',
                'name_ar' => 'QE Transportation',
                'description_en' => 'QE Transportation',
                'description_ar' => 'QE Transportation',
                'short_description_en' => 'QE Transportation',
                'short_description_ar' => 'QE Transportation',
                'full_name' => 'Doha:QETRN',
                'mb_url' => '',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '',
            ],
            [
                'id' => 'e0dbb858-0617-44ae-8bf7-b0a8278a8127',
                'tv_id' => 'QSE:ORDS',
                'symbol' => 'ORDS',
                'isin' => 'QA0007227737',
                'logo_id' => 'ooredoo-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'ORDS',
                'inv_id' => 13219,
                'name_en' => 'OOREDOO QPSC',
                'name_ar' => 'OOREDOO',
                'description_en' => 'Ooredoo QPSC',
                'description_ar' => 'Ooredoo QPSC',
                'short_description_en' => 'Ooredoo QPSC',
                'short_description_ar' => 'Ooredoo QPSC',
                'full_name' => 'Doha:ORDS',
                'mb_url' => '/markets/QE/stocks/ORDS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '59049759-5928-463c-a47c-76f9aa2cf6d9',
            ],
            [
                'id' => 'e1847319-4111-4215-ac5c-5ab6e555f1e0',
                'tv_id' => '',
                'symbol' => 'QEBNK',
                'isin' => '',
                'logo_id' => '',
                'type' => 'index',
                'currency' => 'QAR',
                'inv_symbol' => 'QEBNK',
                'inv_id' => 13182,
                'name_en' => 'Banking',
                'name_ar' => 'Banking',
                'description_en' => 'Banking',
                'description_ar' => 'Banking',
                'short_description_en' => 'Banking',
                'short_description_ar' => 'Banking',
                'full_name' => 'Doha:QEBNK',
                'mb_url' => '',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '',
            ],
            [
                'id' => 'e2249c87-48de-4cf8-a310-c86a2bab8a4c',
                'tv_id' => 'QSE:DUBK',
                'symbol' => 'DUBK',
                'isin' => 'QA000B982PM1',
                'logo_id' => 'dukhan-bank',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'DUBK',
                'inv_id' => 1200403,
                'name_en' => 'DUKHAN BANK QPSC',
                'name_ar' => 'DUKHAN BANK QPSC',
                'description_en' => 'Dukhan Bank QPSC',
                'description_ar' => 'Dukhan Bank QPSC',
                'short_description_en' => 'Dukhan Bank QPSC',
                'short_description_ar' => 'Dukhan Bank QPSC',
                'full_name' => 'Doha:DUBK',
                'mb_url' => '/markets/QE/stocks/DUBK',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => 'e5b99b8b-25a3-4ae8-8e3b-31e780f9c749',
                'tv_id' => 'QSE:QNCD',
                'symbol' => 'QNCD',
                'isin' => 'QA0007227687',
                'logo_id' => 'qatar-national-cement-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QANC',
                'inv_id' => 13218,
                'name_en' => 'QATAR NATIONAL CEMENT QPSC',
                'name_ar' => 'الاسمنت',
                'description_en' => 'Qatar National Cement Co.',
                'description_ar' => 'Qatar National Cement Co.',
                'short_description_en' => 'Qatar National Cement Co.',
                'short_description_ar' => 'Qatar National Cement Co.',
                'full_name' => 'Doha:QANC',
                'mb_url' => '/markets/QE/stocks/QNCD',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '105189b4-0415-4156-a1a3-09266cf8f741',
            ],
            [
                'id' => 'e619cc97-bc9a-41c5-b247-854f93b1d70e',
                'tv_id' => 'QSE:DHBK',
                'symbol' => 'DHBK',
                'isin' => 'QA0006929770',
                'logo_id' => 'doha-bank-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'DOBK',
                'inv_id' => 13189,
                'name_en' => 'DOHA BANK QPSC',
                'name_ar' => 'بنك الدوحة',
                'description_en' => 'Doha Bank',
                'description_ar' => 'Doha Bank',
                'short_description_en' => 'Doha Bank',
                'short_description_ar' => 'Doha Bank',
                'full_name' => 'Doha:DOBK',
                'mb_url' => '/markets/QE/stocks/DHBK',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => 'ee6fab61-3a1d-4e30-84f9-22841bcd5117',
                'tv_id' => 'QSE:QIMD',
                'symbol' => 'QIMD',
                'isin' => 'QA0006929846',
                'logo_id' => 'qatar-industrial-manufacturing-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QIMC',
                'inv_id' => 13215,
                'name_en' => 'QATAR INDUSTRIAL MANUFACTURING QPSC',
                'name_ar' => 'التحويلية',
                'description_en' => 'Qatar Industrial Manufacturing Co',
                'description_ar' => 'Qatar Industrial Manufacturing Co',
                'short_description_en' => 'Qatar Industrial Manufacturing Co',
                'short_description_ar' => 'Qatar Industrial Manufacturing Co',
                'full_name' => 'Doha:QIMC',
                'mb_url' => '/markets/QE/stocks/QIMD',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '5ac5f8ac-198b-4655-88e9-0e08c75ad038',
            ],
            [
                'id' => 'eefa83aa-9510-4092-9bc8-1d7229428ee0',
                'tv_id' => 'QSE:QFBQ',
                'symbol' => 'QFBQ',
                'isin' => 'QA000PLE37B1',
                'logo_id' => 'qatar-first-bank-llc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'QFBQ',
                'inv_id' => 976552,
                'name_en' => 'LESHA BANK LLC',
                'name_ar' => 'الأول',
                'description_en' => 'Lesha Bank LLC',
                'description_ar' => 'Lesha Bank LLC',
                'short_description_en' => 'Lesha Bank LLC',
                'short_description_ar' => 'Lesha Bank LLC',
                'full_name' => 'Doha:QFBQ',
                'mb_url' => '/markets/QE/stocks/QFBQ',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => 'f35bc16e-ad32-48ca-9244-5e236a25b90d',
                'tv_id' => 'QSE:MHAR',
                'symbol' => 'MHAR',
                'isin' => 'QA000IGXGS07',
                'logo_id' => 'al-mahhar-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'MHAR',
                'inv_id' => 1203290,
                'name_en' => 'AL MAHHAR HOLDING QPSC',
                'name_ar' => 'AL MAHHAR HOLDING QPSC',
                'description_en' => 'Al Mahhar Holding Company QPSC',
                'description_ar' => 'Al Mahhar Holding Company QPSC',
                'short_description_en' => 'Al Mahhar Holding Company QPSC',
                'short_description_ar' => 'Al Mahhar Holding Company QPSC',
                'full_name' => 'Doha:MHAR',
                'mb_url' => '/markets/QE/stocks/MHAR',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => '47ebe274-48d3-433d-b4ab-32fd748bd8ad',
            ],
            [
                'id' => 'fab6a867-4e0a-4c96-af6e-74a7a1d4f4e7',
                'tv_id' => 'QSE:IGRD',
                'symbol' => 'IGRD',
                'isin' => 'QA0006UVF886',
                'logo_id' => 'investment-holding-group-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'IGRD',
                'inv_id' => 1055289,
                'name_en' => 'ESTITHMAR HOLDING QPSC',
                'name_ar' => 'استثمار القابضة',
                'description_en' => 'Estithmar Holding QPSC',
                'description_ar' => 'Estithmar Holding QPSC',
                'short_description_en' => 'Estithmar Holding QPSC',
                'short_description_ar' => 'Estithmar Holding QPSC',
                'full_name' => 'Doha:IGRD',
                'mb_url' => '/markets/QE/stocks/IGRD',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
            [
                'id' => 'ffc572e7-3a5a-4d40-8e25-7258dfff5c04',
                'tv_id' => 'QSE:MRDS',
                'symbol' => 'MRDS',
                'isin' => 'QA000A1C6VZ0',
                'logo_id' => 'mazaya-real-estate-development-qpsc',
                'type' => 'stock',
                'currency' => 'QAR',
                'inv_symbol' => 'MRDS',
                'inv_id' => 13567,
                'name_en' => 'MAZAYA REAL ESTATE DEVELOPMENT QPSC',
                'name_ar' => 'مزايا قطر',
                'description_en' => 'Mazaya',
                'description_ar' => 'Mazaya',
                'short_description_en' => 'Mazaya',
                'short_description_ar' => 'Mazaya',
                'full_name' => 'Doha:MRDS',
                'mb_url' => '/markets/QE/stocks/MRDS',
                'status' => 0,
                'country_id' => '4e43d19b-e3af-4aac-8f25-d74b4e3bc21e',
                'market_id' => '71abda1d-afb8-4238-94c5-afb44c3f89ca',
                'sector_id' => 'add59cd8-3881-44fa-a901-461281c0e628',
            ],
        ];

        foreach ($assets as $data) {
            Asset::firstOrCreate(
                ['id' => $data['id']],
                [
                    'tv_id' => ! empty($data['tv_id']) ? $data['tv_id'] : null,
                    'symbol' => $data['symbol'],
                    'isin' => $data['isin'] ?? null,
                    'logo_id' => DB::raw('gen_random_uuid()'),
                    'type' => $data['type'],
                    'currency' => $data['currency'],
                    'inv_symbol' => $data['inv_symbol'],
                    'inv_id' => $data['inv_id'],
                    'name_en' => $data['name_en'],
                    'name_ar' => $data['name_ar'],
                    'description_en' => $data['description_en'],
                    'description_ar' => $data['description_ar'],
                    'short_description_en' => $data['short_description_en'],
                    'short_description_ar' => $data['short_description_ar'],
                    'full_name' => $data['full_name'],
                    'mb_url' => $data['mb_url'] ?? null,
                    'status' => $data['status'],
                    'country_id' => ! empty($data['country_id']) ? $data['country_id'] : null,
                    'market_id' => ! empty($data['market_id']) ? $data['market_id'] : null,
                    'sector_id' => ! empty($data['sector_id']) ? $data['sector_id'] : null,
                ]
            );
        }
    }
}
